apiVersion: v1
kind: Service
metadata:
  name: ebpf-ml-mao-analyzer
  namespace: ebpf-obs
spec:
  selector:
    app: ebpf-ml-mao-analyzer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
