apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ebpf-obs
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - pvc.yaml
  - collector-daemonset.yaml
  - analyzer-service.yaml
  - analyzer-deployment.yaml
