apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: ebpf-obs
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<github-user>",
          "password": "<github-pat-read-packages>",
          "email": "unused@example.com",
          "auth": "<base64(username:token)>"
        }
      }
    }
