apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../step14
  - ui-service.yaml
patches:
  - path: patch-serviceaccounts.yaml
  - path: patch-volume-permissions.yaml
  - path: patch-configmap.yaml
  - path: patch-networkpolicy-dns.yaml
  - path: patch-collector-live-py.yaml
