apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-ml-mao-analyzer
  namespace: ebpf-obs
imagePullSecrets:
  - name: ghcr-pull-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-ml-mao-collector
  namespace: ebpf-obs
imagePullSecrets:
  - name: ghcr-pull-secret
