apiVersion: v1
kind: ConfigMap
metadata:
  name: ebpf-ml-mao-runtime
  namespace: ebpf-obs
data:
  ANALYZER_API_URL: http://ebpf-ml-mao-analyzer.ebpf-obs.svc.cluster.local:8080
  ANALYZER_INGEST_DIR: /var/lib/ebpf-ml-mao/ingest
