apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../step13
images:
  - name: ghcr.io/mlnyuk/ebpf-ml-mao
    newTag: step15
patches:
  - path: patch-configmap.yaml
  - path: patch-analyzer-deployment.yaml
